"""Shared vocabulary and tuning knobs for resume verification."""

from __future__ import annotations

ACTION_VERBS = [
    "achieved",
    "analyzed",
    "architected",
    "automated",
    "built",
    "collaborated",
    "configured",
    "created",
    "decreased",
    "delivered",
    "deployed",
    "designed",
    "developed",
    "engineered",
    "implemented",
    "improved",
    "increased",
    "led",
    "maintained",
    "managed",
    "migrated",
    "monitored",
    "optimized",
    "reduced",
    "secured",
    "shipped",
    "streamlined",
    "tested",
]

BUZZWORDS = [
    "expert",
    "guru",
    "ninja",
    "rockstar",
    "passionate",
    "world class",
    "cutting edge",
    "thought leader",
    "proficient",
]

SKILL_ALIASES: dict[str, list[str]] = {
    "JavaScript": ["javascript", "js", "ecmascript"],
    "TypeScript": ["typescript", "ts"],
    "Python": ["python", "py"],
    "Java": ["java"],
    "C++": ["c++", "cpp"],
    "C#": ["c#", "c sharp"],
    "Go": ["golang", "go"],
    "Rust": ["rust"],
    "SQL": ["sql", "postgresql", "postgres", "mysql", "sqlite"],
    "React": ["react", "react.js", "reactjs"],
    "Node.js": ["node.js", "nodejs", "node"],
    "Express": ["express", "express.js"],
    "FastAPI": ["fastapi"],
    "Django": ["django"],
    "Flask": ["flask"],
    "Spring Boot": ["spring boot"],
    "Docker": ["docker"],
    "Kubernetes": ["kubernetes", "k8s"],
    "Terraform": ["terraform"],
    "Jenkins": ["jenkins"],
    "GitHub Actions": ["github actions"],
    "GitLab CI": ["gitlab ci"],
    "AWS": ["aws", "amazon web services"],
    "Azure": ["azure", "microsoft azure"],
    "Google Cloud": ["gcp", "google cloud"],
    "AWS EKS": ["eks", "aws eks"],
    "MongoDB": ["mongodb", "mongo"],
    "Redis": ["redis"],
    "Kafka": ["kafka", "apache kafka"],
    "Linux": ["linux", "ubuntu", "debian", "red hat", "rhel"],
    "TensorFlow": ["tensorflow"],
    "PyTorch": ["pytorch", "torch"],
    "scikit-learn": ["scikit-learn", "sklearn"],
    "LangChain": ["langchain"],
    "OpenAI": ["openai", "gpt", "chatgpt"],
    "NLP": ["nlp", "natural language processing"],
    "OCR": ["ocr", "optical character recognition"],
    "Nmap": ["nmap"],
    "Burp Suite": ["burp suite", "burp"],
    "Wireshark": ["wireshark"],
    "Metasploit": ["metasploit"],
    "SIEM": ["siem", "splunk", "sentinel"],
    "REST APIs": ["rest api", "rest apis", "restful api", "rest"],
    "GraphQL": ["graphql"],
    "CI/CD": ["ci/cd", "cicd", "continuous integration"],
    "Agile": ["agile", "scrum"],
    "AWS Certified": ["aws certified", "aws certification"],
    "Azure Certified": ["azure certified", "azure certification"],
    "Security+": ["security+", "comptia security"],
    "CISSP": ["cissp"],
}

DOMAIN_TERMS = {
    "cloud": ["cloud", "aws", "azure", "gcp", "serverless", "eks", "ec2", "s3"],
    "devops": ["devops", "ci/cd", "docker", "kubernetes", "terraform", "jenkins"],
    "security": ["security", "cybersecurity", "siem", "nmap", "burp", "wireshark", "vulnerability"],
    "ai/ml": ["ai", "ml", "machine learning", "deep learning", "tensorflow", "pytorch", "langchain"],
    "backend": ["api", "backend", "database", "microservices", "node", "fastapi", "express"],
    "frontend": ["frontend", "react", "typescript", "ui", "web"],
}

STRICTNESS = {
    "low": {"min_evidence": 1, "missing_penalty": 20, "inflated_penalty": 8, "weak_threshold": 45},
    "medium": {"min_evidence": 1, "missing_penalty": 30, "inflated_penalty": 14, "weak_threshold": 55},
    "high": {"min_evidence": 2, "missing_penalty": 42, "inflated_penalty": 24, "weak_threshold": 70},
}

EVIDENCE_LEVELS = frozenset({"demonstrated", "supported", "mentioned", "weak", "missing"})

SECTION_WEIGHT = {
    "experience": 40,
    "projects": 25,
    "achievements": 15,
    "certifications": 10,
    "education": 8,
    "skills": 5,
    "summary": 6,
    "other": 3,
}
